//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevTools.Analyzers.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevTools.Analyzers.Exceptions.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reserved exception should not be thrown..
        /// </summary>
        public static string ReservedExceptionDiagnosticDescription {
            get {
                return ResourceManager.GetString("ReservedExceptionDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not throw &apos;{0}&apos;. {1}.
        /// </summary>
        public static string ReservedExceptionDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("ReservedExceptionDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider throwing &apos;{0}&apos; instead..
        /// </summary>
        public static string ReservedExceptionDiagnosticReplacementFormat {
            get {
                return ResourceManager.GetString("ReservedExceptionDiagnosticReplacementFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved exception thrown.
        /// </summary>
        public static string ReservedExceptionDiagnosticTitle {
            get {
                return ResourceManager.GetString("ReservedExceptionDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unspecific exception should not be thrown..
        /// </summary>
        public static string UnspecificExceptionDiagnosticDescription {
            get {
                return ResourceManager.GetString("UnspecificExceptionDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not throw &apos;{0}&apos;. Throw a more specific exception..
        /// </summary>
        public static string UnspecificExceptionDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("UnspecificExceptionDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecific exception thrown.
        /// </summary>
        public static string UnspecificExceptionDiagnosticTitle {
            get {
                return ResourceManager.GetString("UnspecificExceptionDiagnosticTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception should be created and thrown in the same line..
        /// </summary>
        public static string VariableExceptionDiagnosticDescription {
            get {
                return ResourceManager.GetString("VariableExceptionDiagnosticDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not throw an exception that is not created in the same line..
        /// </summary>
        public static string VariableExceptionDiagnosticMessageFormat {
            get {
                return ResourceManager.GetString("VariableExceptionDiagnosticMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable exception thrown.
        /// </summary>
        public static string VariableExceptionDiagnosticTitle {
            get {
                return ResourceManager.GetString("VariableExceptionDiagnosticTitle", resourceCulture);
            }
        }
    }
}
